---
- hosts: kafka
  remote_user: root
  roles:
    - init_ssh
    - init_ansible
    - init_update
    - hostname
    - shell
    - common_pkgs
    - zookeeper
    - kafka
    - xxxpool_kafka-topics
